### ISSUE TITLE
One-way ANOVA null hypothesis: B1 or B0?

### ISSUE THREAD

**Issue by thorbjornwolf** [lindeloev/tests-as-linear#11]
Maybe I'm misunderstanding it, but shouldn't the one-way ANOVA null hypothesis be $y = \beta_0$, not $y = \beta_1$?

$\beta_0$ is the mean of the first group, no? Is this a case of 0-indexing vs 1-indexing? :smile:

**Comment by lindeloev** [comment]
Thanks for the catch, Thorbjørn! The fixed doc will go live in a minute.
