### ISSUE TITLE
Cheat sheet: Kruskal-Wallis changes

### ISSUE THREAD

**Issue by WilDoane** [lindeloev/tests-as-linear#14]
Common name should be Kruskal-Wallis (sheet has an extra L)
Linear Model in Words should read "Same, but it predicts the rank of y" (currently reads "signed rank")

**Comment by lindeloev** [comment]
Thank you, William! I love the way these bugs are weeded out by putting it on GitHub. Around 60.000 views of the cheat sheet, and you were the first to report it ;-) I fixed it now.
