### ISSUE TITLE
Output for Wilcoxon signed-rank test correct?

### ISSUE THREAD

**Issue by SteveRxD** [lindeloev/tests-as-linear#17]
Hi, thanks for this great resource! I'm working through the book now. 

Can I confirm that the p-values published in the table of section '_4.1.3 R code: Wilcoxon signed-rank test_' are correct? I get different p-values for both the Wilcoxon test and the linear model using signed ranks (0.2628 and 02650 respectively). I have been able to replicate all other tests in the book so far using the toy data set. Thanks.

**Comment by lindeloev** [comment]
They are not completely identical, as are none of the non-parametric "equivalents". In your case, p is off by 0.0022. This, you can also see in the website version.

Or are you pointing to a different issue?

**Comment by SteveRxD** [comment]
My apologies, I see the problem - it was to do with the toy data. When reproducing your work I created the toy data sets  in a different order (x, y, y2 instead of y, x, y2). When I ran it again I get the same results as you.
