### ISSUE TITLE
aov is a wrapper for lm

### ISSUE THREAD

**Issue by aghaynes** [lindeloev/tests-as-linear#7]
This is a great cheat sheet and comparison of the methods that you've made. Thanks for taking the time to think about it and write it up!

One small comment....
I'm sure you're aware, but aov is just a wrapper for lm with some specific settings (e.g. Helmut contrasts) and print/summary methods to approximate a classical ANOVA table, so it's be difficult for the models to return something different... the way section 6.1.3 is written at the moment feels a bit like you're surprised that they yield the same thing.

Cheers!

**Comment by lindeloev** [comment]
You are right that the wording is not lucky. I've tried and fix it. What do you think?

The value of showing `aov` and `car::Anova` is that one can see that the explicit way of writing out main effects and interactions is equivalent to the simple `y ~ group*sex`. Of course, that would be the same if we did it in `aov`, but it still show that you need no specialized function to do an ANOVA.

**Comment by aghaynes** [comment]
It's better, but I think there's a few points still. 
You're modelling with aov and lm, where the former just wraps the latter anyway. 
car::Anova isn't "built-in", it's in the car package
anova and/or car::Anova prepare the output into a nice ANOVA table
I think you actually mean anova when you talk about type 1 SS
Because aov wraps lm, you can actually use everything on an aov object that you can use on the lm - means that you can get the coefficients coef(aov(value ~ group, D)), even though it's not as immediately obvious. I just checked, this is similar in Stata, so I guess most packages must use regression to do the work and just have a different print method for ANOVAs.

How about...
OK, let’s compare an ANOVA using aov and car::Anova with the dummy-coded in-your-face linear model in lm. The results are practically identical (only the DF differs). The latter visibly returns parameter estimates in the output as well (although they're also available via aov), but we’ll just look at the overall model statistics for now. 

This bit could go after the table perhaps... I think it confuses the main point.
For those interested in the details, aov is just a wrapper for lm so the identity should come as no surprise. This means that parameter estimates are also available for ANOVA. Indeed, the only real reason to use aov and car::Anova rather than lm is to get a nicely formatted ANOVA table. Also note that I use car::Anova rather than the stats::anova (the built-in anova function) because it computes type-II sum of squares rather than type-I SS as stats::anova does. There is a BIG polarized debate about whether to use type-II (as car::Anova does by default) or type-III sum of squares, but let’s skip that for now.

**Comment by aghaynes** [comment]
Hmmm...that's a little longer than I expected... I'll do a PR next time perhaps

**Comment by lindeloev** [comment]
Will look at this in the weekend. Reopening.

Thanks for not letting me get away with this, Alan :-)

**Comment by lindeloev** [comment]
Hi again, @aghaynes. I agree with everything and have tried to address it in the latest commit. What do you think?

(Both `aov` and `anova` default to type-I SS)

**Comment by aghaynes** [comment]
Hi! Much better... the only inaccuracy that I noticed was that aov is the wrapper for lm. car::Anova *just* (not sure that's the right word as there's a bit more to it than that) formats/prepares the ANOVA table.
