### ISSUE TITLE
Add explaination of rank() to text

### ISSUE THREAD

**Issue by kaspermarstal** [lindeloev/tests-as-linear#9]
Thanks for this great resource! In the section on Pearson Correlation, what is `rank(x)`? Did I miss it? If not, I suggest to elaborate on this in the text as I am probably not the only one with this question. Awesome work!

**Comment by kaspermarstal** [comment]
Aahh, it is in section 3.0.3.

**Comment by lindeloev** [comment]
Great idea/catch. Will do that, or at least link to a pedagogical resource. I'm hoping to do it before the weekend is over.

**Comment by lindeloev** [comment]
I just added some theory on ranks. Let me know what you think.
